server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/fitness-realm

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/usuarios/**
        - id: membresia-service
          uri: lb://membresia-service
          predicates:
            - Path=/api/membresias/**
        - id: rutina-service
          uri: lb://rutina-service
          predicates:
            - Path=/api/rutinas/**
        - id: ejercicio-rutina-service
          uri: lb://ejercicio-rutina-service
          predicates:
            - Path=/api/ejercicios-rutina/**
        - id: progreso-service
          uri: lb://progreso-service
          predicates:
            - Path=/api/progresos/**
        - id: nutricion-service
          uri: lb://nutricion-service
          predicates:
            - Path=/api/nutriciones/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
