server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: usuario-service-route
          uri: lb://usuario-service
          predicates:
            - Path=/api/usuarios/**

        - id: membresia-service-route
          uri: lb://membresia-service
          predicates:
            - Path=/api/membresias/**

        - id: rutina-service-route
          uri: lb://rutina-service
          predicates:
            - Path=/api/rutinas/**

        - id: ejercicio-rutina-service-route
          uri: lb://ejercicio-rutina-service
          predicates:
            - Path=/api/ejercicios-rutina/**

        - id: progreso-service-route
          uri: lb://progreso-service
          predicates:
            - Path=/api/progresos/**

        - id: nutricion-service-route
          uri: lb://nutricion-service
          predicates:
            - Path=/api/nutriciones/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true